contact_links:
  - name: Help or Questions 🙀
    url: https://github.com/geist-org/geistclone/discussions
    about: This issue tracker is not for support questions. Please refer to the Github's Discussions.
